image: ghcr.io/jethub-homeassistant/{machine}-homeassistant
build_from:
  aarch64: scratch
  armv7: scratch
  armhf: scratch
  amd64: scratch
  i386: scratch
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
cosign:
  base_identity: https://github.com/jethub-homeassistant/docker-base/.*
  identity: https://github.com/jethub-homeassistant/landingpage/.*
labels:
  io.hass.type: landingpage
  org.opencontainers.image.source: https://github.com/jethub-homeassistant/landingpage
