name: Build landingpage

on:
  pull_request:
    branches: ["main"]
  release:
    types: ["published"]

jobs:
  build:
    name: Build landingpage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - generic-x86-64
          - intel-nuc
          - khadas-vim3
          - jethub-h1
          - jethub-h2
          - jethub-d1
          - jethub-d1p
          - odroid-c2
          - odroid-c4
          - odroid-m1
          - odroid-n2
          - qemuarm
          - qemuarm-64
          - qemux86
          - qemux86-64
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'release'
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      if: github.event_name == 'release'
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set build arguments
      if: github.event_name != 'release'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

    - name: Build landingpage
      uses: jethub-homeassistant/builder@2023.03.0
      with:
        args: |
          $BUILD_ARGS \
          --target /data \
          --no-latest \
          --machine landingpage=${{ matrix.machine }}
      env:
        CAS_API_KEY: ${{ secrets.CAS_TOKEN }}
